# Liste de phrases réconfortantes
phrases_reconfortantes = [
    "Tu es sur la bonne voie, ne doute jamais de ton potentiel.",
    "Chaque obstacle que tu rencontres est une opportunité d'apprendre et de grandir.",
    "N'oublie pas que la recherche est un voyage, et chaque pas compte.",
    "Ton travail a un impact réel, même si cela peut sembler décourageant parfois.",
    "N'oublie pas de prendre soin de toi, tant physiquement que mentalement.",
    "La persévérance est la clé du succès, continue à avancer.",
    "Tu es capable de surmonter les moments difficiles, tu es plus fort que tu ne le penses.",
    "N'oublie pas que tu es entouré de personnes prêtes à t'aider, n'hésite pas à demander de l'aide.",
    "Chaque petit progrès te rapproche de l'achèvement de ta thèse.",
    "Ta passion pour ta recherche est une source inestimable de motivation.",
    "Même quand tout semble sombre, rappelle-toi que chaque découverte que tu fais est précieuse.",
    "Le travail acharné que tu mets dans ta thèse portera ses fruits à long terme.",
    "N'oublie pas de célébrer chaque étape de ton voyage académique, aussi petite soit-elle.",
    "Les moments de doute sont temporaires, mais la réussite est durable.",
    "Ta thèse est un témoignage de ta détermination et de ta persévérance.",
    "N'oublie pas que tu es en train de contribuer à l'expansion des connaissances dans ton domaine.",
    "La recherche est un voyage de découverte et d'apprentissage, et tu es un explorateur.",
    "Les erreurs font partie du processus, ne les crains pas, apprends d'elles.",
    "Ton enthousiasme pour ta recherche est contagieux, continue à le cultiver.",
    "Chaque mot que tu écris est une pierre angulaire de ta thèse, tu es en train de construire quelque chose de grand.",
    "La patience et la persévérance te guideront à travers les moments difficiles.",
    "N'oublie pas que tu es soutenu par une communauté de chercheurs qui se soucient de ton succès.",
    "Ton travail est important et il contribuera à l'avancement des connaissances dans ton domaine.",
    "La réussite nécessite du temps, mais chaque heure de recherche te rapproche de ton objectif.",
    "N'oublie pas de prendre des pauses pour te ressourcer, ta santé mentale est précieuse.",
    "Ta thèse est une aventure intellectuelle incroyable, profite de chaque moment.",
    "Chaque chapitre que tu écris t'approche un peu plus de l'achèvement de ta thèse.",
    "La créativité et l'innovation sont au cœur de la recherche, tu es sur la bonne voie.",
    "N'oublie pas que chaque contribution que tu fais a un impact réel dans le monde académique.",
    "Les moments de découragement ne font que renforcer ta détermination à réussir.",
    "Ton travail est précieux, et il mérite d'être partagé avec le monde.",
    "Chaque petite victoire te rapproche de ton objectif, ne les sous-estime jamais.",
    "La confiance en toi est la clé de la réussite, crois en toi et en tes capacités.",
    "N'oublie pas que la recherche est un processus, et chaque étape te rapproche de la fin.",
    "La passion que tu mets dans ta recherche brille à travers ton travail, c'est inspirant.",
    "La persévérance est la force qui te permet de surmonter les défis, continue à avancer.",
    "N'oublie pas que tu es en train de créer de nouvelles connaissances, c'est une réalisation exceptionnelle.",
    "Ta thèse est un témoignage de ton engagement envers la découverte et la compréhension.",
    "Le succès n'est pas une ligne droite, mais une série d'étapes, et tu les franchis avec détermination.",
    "N'oublie pas de prendre du temps pour toi, cela te permettra de maintenir un équilibre sain.",
    "Ton diplôme de doctorat est à ta portée, continue à travailler dur pour l'atteindre.",
    "La patience est essentielle dans la recherche, chaque moment compte dans ton voyage académique.",
    "N'oublie pas que tu es en train de contribuer à l'expansion des connaissances dans ton domaine.",
    "Les moments de doute ne définissent pas ton potentiel, ils sont simplement des obstacles temporaires.",
    "Ton travail est une contribution précieuse à la connaissance, ne sous-estime jamais son importance.",
    "Chaque petit pas t'approche un peu plus de l'achèvement de ta thèse, ne perds pas de vue cet objectif.",
    "La recherche est une aventure, et tu es en train de vivre une expérience incroyable.",
    "N'oublie pas que tu es soutenu par des amis, des collègues et des mentors, ils croient en toi.",
    "Les défis que tu rencontres sont des opportunités d'apprendre et de grandir, ils font partie du voyage.",
    "Ton enthousiasme et ta passion pour ta recherche sont contagieux, continue à les nourrir.",
    "Chaque jour est une nouvelle opportunité de progresser, ne perds pas de vue tes objectifs.",
    "N'oublie pas que chaque mot que tu écris te rapproche un peu plus de la fin de ta thèse.",
    "La confiance en toi est essentielle pour surmonter les obstacles, crois en tes compétences.",
    "N'oublie pas de célébrer tes réalisations, aussi petites soient-elles, elles comptent énormément.",
    "Les moments de doute sont naturels, mais ils ne doivent pas éclipser ta confiance en toi.",
    "Ta thèse a un impact réel, même si cela peut prendre du temps pour le voir se concrétiser.",
    "N'oublie pas que tu as déjà surmonté des obstacles pour en arriver là où tu es aujourd'hui.",
    "La persévérance est ta plus grande alliée, continue à avancer avec détermination.",
    "Lorsque tu te sens dépassé, rappelle-toi pourquoi tu as commencé cette recherche, cela te remotivera.",
    "La science a besoin de chercheurs passionnés comme toi pour progresser.",
    "Ton travail de recherche est important, et il laissera une empreinte durable dans ton domaine.",
    "Les moments de frustration font partie du voyage, ne les laisse pas te décourager, ils te rendent plus fort.",
    "Ton enthousiasme pour ta recherche est contagieux, il inspire les autres autour de toi.",
    "La patience et la détermination sont essentielles pour traverser les moments difficiles.",
    "N'oublie pas que tu es en train de créer de nouvelles connaissances et de repousser les limites de la compréhension humaine.",
    "Ton travail est précieux, ne sous-estime jamais son importance.",
    "Chaque petit progrès te rapproche de l'achèvement de ta thèse, continue d'avancer, un pas à la fois.",
    "La confiance en toi est le moteur de ton succès, crois en toi et en tes compétences.",
    "N'oublie pas de prendre du temps pour te ressourcer et te recentrer, cela est essentiel pour ton bien-être.",
    "Ton diplôme de doctorat est à ta portée, tu es sur la bonne voie pour l'atteindre.",
    "La recherche est un voyage d'exploration et de découverte, continue d'explorer avec passion.",
    "Chaque chapitre que tu écris est une victoire en soi, ne sous-estime pas l'importance de chaque étape.",
    "La créativité et l'innovation sont au cœur de la recherche, et tu es un créateur de connaissances.",
    "Les moments de doute ne font que renforcer ta détermination à réussir, ne les laisse pas te décourager.",
    "Ton travail est une contribution précieuse à la connaissance, ne sous-estime jamais son impact.",
    "Chaque jour apporte de nouvelles opportunités de réussite, saisis-les avec détermination.",
    "Tu as déjà surmonté des obstacles pour en arriver là où tu es, tu es capable de surmonter ceux qui se présentent encore.",
    "La persévérance est la clé pour surmonter les obstacles, continue à avancer avec force et courage.",
    "Lorsque tu te sens dépassé, rappelle-toi pourquoi tu as entrepris cette recherche et la passion qui t'anime.",
    "La science a besoin de chercheurs passionnés comme toi pour avancer et éclairer le monde.",
    "Ton travail de recherche est important, et il laissera une trace durable dans ton domaine.",
    "Les moments de frustration font partie du voyage, mais ils ne doivent pas entamer ta détermination.",
    "Ton enthousiasme pour ta recherche est contagieux, il inspire ceux qui t'entourent.",
    "La patience et la détermination sont les clés pour traverser les moments difficiles.",
    "N'oublie pas que tu es en train de créer de nouvelles connaissances et de repousser les frontières de la compréhension humaine.",
    "Ton travail est précieux, et il mérite d'être célébré à chaque étape.",
    "Chaque petit progrès te rapproche de l'achèvement de ta thèse, continue d'avancer, un pas à la fois.",
    "La confiance en toi est le moteur de ton succès, continue de croire en toi-même et en ton travail.",
    "N'oublie pas de prendre du temps pour te ressourcer et prendre soin de toi, cela est essentiel pour ton bien-être.",
    "Ton diplôme de doctorat est à ta portée, continue de travailler avec acharnement pour l'atteindre.",
    "La recherche est un voyage d'exploration et de découverte, continue d'explorer avec passion.",
    "Chaque chapitre que tu écris est une victoire en soi, ne sous-estime pas l'importance de chaque étape.",
    "La créativité et l'innovation sont au cœur de la recherche, et tu es un créateur de connaissances.",
    "Les moments de doute ne font que renforcer ta détermination à réussir, ne les laisse pas te décourager.",
    "Ton travail est une contribution précieuse à la connaissance, ne sous-estime jamais son impact.",
    "Chaque jour apporte de nouvelles opportunités de réussite, saisis-les avec détermination.",
    "Tu as déjà surmonté des obstacles pour en arriver là où tu es, tu es capable de surmonter ceux qui se présentent encore.",
    "La persévérance est la clé pour surmonter les obstacles, continue à avancer avec force et courage.",
    "Lorsque tu te sens dépassé, rappelle-toi pourquoi tu as entrepris cette recherche et la passion qui t'anime.",
    "La science a besoin de chercheurs passionnés comme toi pour avancer et éclairer le monde.",
    "Ton travail de recherche est important, et il laissera une trace durable dans ton domaine.",
    "Les moments de frustration font partie du voyage, mais ils ne doivent pas entamer ta détermination.",
    "Ton enthousiasme pour ta recherche est contagieux, il inspire ceux qui t'entourent.",
    "La patience et la détermination sont les clés pour traverser les moments difficiles.",
    "N'oublie pas que tu es en train de créer de nouvelles connaissances et de repousser les frontières de la compréhension humaine.",
    "Ton travail est précieux, et il mérite d'être célébré à chaque étape.",
    "Chaque petit progrès te rapproche de l'achèvement de ta thèse, continue d'avancer, un pas à la fois.",
    "La confiance en toi est le moteur de ton succès, continue de croire en toi-même et en ton travail.",
    "N'oublie pas de prendre du temps pour te ressourcer et prendre soin de toi, cela est essentiel pour ton bien-être.",
    "Ton diplôme de doctorat est à ta portée, continue de travailler avec acharnement pour l'atteindre.",
    "La recherche est un voyage d'exploration et de découverte, continue d'explorer avec passion.",
    "Chaque chapitre que tu écris est une victoire en soi, ne sous-estime pas l'importance de chaque étape.",
    "La créativité et l'innovation sont au cœur de la recherche, et tu es un créateur de connaissances.",
    "Les moments de doute ne font que renforcer ta détermination à réussir, ne les laisse pas te décourager.",
    "Ton travail est une contribution précieuse à la connaissance, ne sous-estime jamais son impact.",
    "Chaque jour apporte de nouvelles opportunités de réussite, saisis-les avec détermination.",
    "Tu as déjà surmonté des obstacles pour en arriver là où tu es, tu es capable de surmonter ceux qui se présentent encore.",
    "La persévérance est la clé pour surmonter les obstacles, continue à avancer avec force et courage.",
    "Lorsque tu te sens dépassé, rappelle-toi pourquoi tu as entrepris cette recherche et la passion qui t'anime.",
    "La science a besoin de chercheurs passionnés comme toi pour avancer et éclairer le monde.",
    "Ton travail de recherche est important, et il laissera une trace durable dans ton domaine.",
    "Les moments de frustration font partie du voyage, mais ils ne doivent pas entamer ta détermination.",
    "Ton enthousiasme pour ta recherche est contagieux, il inspire ceux qui t'entourent.",
    "La patience et la détermination sont les clés pour traverser les moments difficiles.",
    "N'oublie pas que tu es en train de créer de nouvelles connaissances et de repousser les frontières de la compréhension humaine.",
    "Ton travail est précieux, et il mérite d'être célébré à chaque étape.",
    "Chaque petit progrès te rapproche de l'achèvement de ta thèse, continue d'avancer, un pas à la fois.",
    "La confiance en toi est le moteur de ton succès, continue de croire en toi-même et en ton travail.",
    "N'oublie pas de prendre du temps pour te ressourcer et prendre soin de toi, cela est essentiel pour ton bien-être.",
    "Ton diplôme de doctorat est à ta portée, continue de travailler avec acharnement pour l'atteindre.",
    "La recherche est un voyage d'exploration et de découverte, continue d'explorer avec passion.",
    "Chaque chapitre que tu écris est une victoire en soi, ne sous-estime pas l'importance de chaque étape.",
    "La créativité et l'innovation sont au cœur de la recherche, et tu es un créateur de connaissances.",
    "Les moments de doute ne font que renforcer ta détermination à réussir, ne les laisse pas te décourager.",
    "Ton travail est une contribution précieuse à la connaissance, ne sous-estime jamais son impact.",
    "Chaque jour apporte de nouvelles opportunités de réussite, saisis-les avec détermination.",
    "Tu as déjà surmonté des obstacles pour en arriver là où tu es, tu es capable de surmonter ceux qui se présentent encore.",
    "La persévérance est la clé pour surmonter les obstacles, continue à avancer avec force et courage.",
    "Lorsque tu te sens dépassé, rappelle-toi pourquoi tu as entrepris cette recherche et la passion qui t'anime.",
    "La science a besoin de chercheurs passionnés comme toi pour avancer et éclairer le monde.",
    "Ton travail de recherche est important, et il laissera une trace durable dans ton domaine.",
    "Les moments de frustration font partie du voyage, mais ils ne doivent pas entamer ta détermination.",
    "Ton enthousiasme pour ta recherche est contagieux, il inspire ceux qui t'entourent.",
    "La patience et la détermination sont les clés pour traverser les moments difficiles.",
    "N'oublie pas que tu es en train de créer de nouvelles connaissances et de repousser les frontières de la compréhension humaine.",
    "Ton travail est précieux, et il mérite d'être célébré à chaque étape.",
    "Chaque petit progrès te rapproche de l'achèvement de ta thèse, continue d'avancer, un pas à la fois.",
    "La confiance en toi est le moteur de ton succès, continue de croire en toi-même et en ton travail.",
    "N'oublie pas de prendre du temps pour te ressourcer et prendre soin de toi, cela est essentiel pour ton bien-être.",
    "Ton diplôme de doctorat est à ta portée, continue de travailler avec acharnement pour l'atteindre.",
    "La recherche est un voyage d'exploration et de découverte, continue d'explorer avec passion.",
    "Chaque chapitre que tu écris est une victoire en soi, ne sous-estime pas l'importance de chaque étape.",
    "La créativité et l'innovation sont au cœur de la recherche, et tu es un créateur de connaissances.",
    "Les moments de doute ne font que renforcer ta détermination à réussir, ne les laisse pas te décourager.",
    "Ton travail est une contribution précieuse à la connaissance, ne sous-estime jamais son impact.",
    "Chaque jour apporte de nouvelles opportunités de réussite, saisis-les avec détermination.",
    "Tu as déjà surmonté des obstacles pour en arriver là où tu es, tu es capable de surmonter ceux qui se présentent encore.",
    "La persévérance est la clé pour surmonter les obstacles, continue à avancer avec force et courage.",
    "Lorsque tu te sens dépassé, rappelle-toi pourquoi tu as entrepris cette recherche et la passion qui t'anime.",
    "La science a besoin de chercheurs passionnés comme toi pour avancer et éclairer le monde.",
    "Ton travail de recherche est important, et il laissera une trace durable dans ton domaine.",
    "Les moments de frustration font partie du voyage, mais ils ne doivent pas entamer ta détermination.",
    "Ton enthousiasme pour ta recherche est contagieux, il inspire ceux qui t'entourent.",
    "La patience et la détermination sont les clés pour traverser les moments difficiles.",
    "N'oublie pas que tu es en train de créer de nouvelles connaissances et de repousser les frontières de la compréhension humaine.",
    "Ton travail est précieux, et il mérite d'être célébré à chaque étape.",
    "Chaque petit progrès te rapproche de l'achèvement de ta thèse, continue d'avancer, un pas à la fois.",
    "La confiance en toi est le moteur de ton succès, continue de croire en toi-même et en ton travail.",
    "N'oublie pas de prendre du temps pour te ressourcer et prendre soin de toi, cela est essentiel pour ton bien-être.",
    "Ton diplôme de doctorat est à ta portée, continue de travailler avec acharnement pour l'atteindre.",
    "La recherche est un voyage d'exploration et de découverte, continue d'explorer avec passion.",
    "Chaque chapitre que tu écris est une victoire en soi, ne sous-estime pas l'importance de chaque étape.",
    "La créativité et l'innovation sont au cœur de la recherche, et tu es un créateur de connaissances.",
    "Les moments de doute ne font que renforcer ta détermination à réussir, ne les laisse pas te décourager.",
    "Ton travail est une contribution précieuse à la connaissance, ne sous-estime jamais son impact.",
    "Chaque jour apporte de nouvelles opportunités de réussite, saisis-les avec détermination.",
    "Tu as déjà surmonté des obstacles pour en arriver là où tu es, tu es capable de surmonter ceux qui se présentent encore.",
    "La persévérance est la clé pour surmonter les obstacles, continue à avancer avec force et courage.",
    "Lorsque tu te sens dépassé, rappelle-toi pourquoi tu as entrepris cette recherche et la passion qui t'anime.",
    "La science a besoin de chercheurs passionnés comme toi pour avancer et éclairer le monde.",
    "Ton travail de recherche est important, et il laissera une trace durable dans ton domaine.",
    "Les moments de frustration font partie du voyage, mais ils ne doivent pas entamer ta détermination.",
    "Ton enthousiasme pour ta recherche est contagieux, il inspire ceux qui t'entourent.",
    "La patience et la détermination sont les clés pour traverser les moments difficiles.",
    "N'oublie pas que tu es en train de créer de nouvelles connaissances et de repousser les frontières de la compréhension humaine.",
    "Ton travail est précieux, et il mérite d'être célébré à chaque étape.",
    "Chaque petit progrès te rapproche de l'achèvement de ta thèse, continue d'avancer, un pas à la fois.",
    "La confiance en toi est le moteur de ton succès, continue de croire en toi-même et en ton travail.",
    "N'oublie pas de prendre du temps pour te ressourcer et prendre soin de toi, cela est essentiel pour ton bien-être.",
    "Ton diplôme de doctorat est à ta portée, continue de travailler avec acharnement pour l'atteindre.",
    "La recherche est un voyage d'exploration et de découverte, continue d'explorer avec passion.",
    "Chaque chapitre que tu écris est une victoire en soi, ne sous-estime pas l'importance de chaque étape.",
    "La créativité et l'innovation sont au cœur de la recherche, et tu es un créateur de connaissances.",
    "Les moments de doute ne font que renforcer ta détermination à réussir, ne les laisse pas te décourager.",
    "Ton travail est une contribution précieuse à la connaissance, ne sous-estime jamais son impact.",
    "Chaque jour apporte de nouvelles opportunités de réussite, saisis-les avec détermination.",
    "Tu as déjà surmonté des obstacles pour en arriver là où tu es, tu es capable de surmonter ceux qui se présentent encore.",
    "La persévérance est la clé pour surmonter les obstacles, continue à avancer avec force et courage.",
    "Lorsque tu te sens dépassé, rappelle-toi pourquoi tu as entrepris cette recherche et la passion qui t'anime.",
    "La science a besoin de chercheurs passionnés comme toi pour avancer et éclairer le monde.",
    "Ton travail de recherche est important, et il laissera une trace durable dans ton domaine.",
    "Les moments de frustration font partie du voyage, mais ils ne doivent pas entamer ta détermination.",
    "Ton enthousiasme pour ta recherche est contagieux, il inspire ceux qui t'entourent.",
    "La patience et la détermination sont les clés pour traverser les moments difficiles.",
    "N'oublie pas que tu es en train de créer de nouvelles connaissances et de repousser les frontières de la compréhension humaine.",
    "Ton travail est précieux, et il mérite d'être célébré à chaque étape.",
    "Chaque petit progrès te rapproche de l'achèvement de ta thèse, continue d'avancer, un pas à la fois.",
    "La confiance en toi est le moteur de ton succès, continue de croire en toi-même et en ton travail.",
    "N'oublie pas de prendre du temps pour te ressourcer et prendre soin de toi, cela est essentiel pour ton bien-être.",
    "Ton diplôme de doctorat est à ta portée, continue de travailler avec acharnement pour l'atteindre.",
    "La recherche est un voyage d'exploration et de découverte, continue d'explorer avec passion.",
    "Chaque chapitre que tu écris est une victoire en soi, ne sous-estime pas l'importance de chaque étape.",
    "La créativité et l'innovation sont au cœur de la recherche, et tu es un créateur de connaissances.",
    "Les moments de doute ne font que renforcer ta détermination à réussir, ne les laisse pas te décourager.",
    "Ton travail est une contribution précieuse à la connaissance, ne sous-estime jamais son impact.",
    "Chaque jour apporte de nouvelles opportunités de réussite, saisis-les avec détermination.",
    "Tu as déjà surmonté des obstacles pour en arriver là où tu es, tu es capable de surmonter ceux qui se présentent encore.",
    "La persévérance est la clé pour surmonter les obstacles, continue à avancer avec force et courage.",
    "Lorsque tu te sens dépassé, rappelle-toi pourquoi tu as entrepris cette recherche et la passion qui t'anime.",
    "La science a besoin de chercheurs passionnés comme toi pour avancer et éclairer le monde.",
    "Ton travail de recherche est important, et il laissera une trace durable dans ton domaine.",
    "Les moments de frustration font partie du voyage, mais ils ne doivent pas entamer ta détermination.",
    "Ton enthousiasme pour ta recherche est contagieux, il inspire ceux qui t'entourent.",
    "La patience et la détermination sont les clés pour traverser les moments difficiles.",
    "N'oublie pas que tu es en train de créer de nouvelles connaissances et de repousser les frontières de la compréhension humaine.",
    "Ton travail est précieux, et il mérite d'être célébré à chaque étape.",
    "Chaque petit progrès te rapproche de l'achèvement de ta thèse, continue d'avancer, un pas à la fois.",
    "La confiance en toi est le moteur de ton succès, continue de croire en toi-même et en ton travail.",
    "N'oublie pas de prendre du temps pour te ressourcer et prendre soin de toi, cela est essentiel pour ton bien-être.",
    "Ton diplôme de doctorat est à ta portée, continue de travailler avec acharnement pour l'atteindre.",
    "La recherche est un voyage d'exploration et de découverte, continue d'explorer avec passion.",
    "Chaque chapitre que tu écris est une victoire en soi, ne sous-estime pas l'importance de chaque étape.",
    "La créativité et l'innovation sont au cœur de la recherche, et tu es un créateur de connaissances.",
    "Les moments de doute ne font que renforcer ta détermination à réussir, ne les laisse pas te décourager.",
    "Ton travail est une contribution précieuse à la connaissance, ne sous-estime jamais son impact.",
    "Chaque jour apporte de nouvelles opportunités de réussite, saisis-les avec détermination.",
    "Tu as déjà surmonté des obstacles pour en arriver là où tu es, tu es capable de surmonter ceux qui se présentent encore.",
    "La persévérance est la clé pour surmonter les obstacles, continue à avancer avec force et courage.",
    "Lorsque tu te sens dépassé, rappelle-toi pourquoi tu as entrepris cette recherche et la passion qui t'anime.",
    "La science a besoin de chercheurs passionnés comme toi pour avancer et éclairer le monde.",
    "Ton travail de recherche est important, et il laissera une trace durable dans ton domaine.",
    "Les moments de frustration font partie du voyage, mais ils ne doivent pas entamer ta détermination.",
    "Ton enthousiasme pour ta recherche est contagieux, il inspire ceux qui t'entourent.",
    "La patience et la détermination sont les clés pour traverser les moments difficiles.",
    "N'oublie pas que tu es en train de créer de nouvelles connaissances et de repousser les frontières de la compréhension humaine.",
    "Ton travail est précieux, et il mérite d'être célébré à chaque étape.",
    "Chaque petit progrès te rapproche de l'achèvement de ta thèse, continue d'avancer, un pas à la fois.",
    "La confiance en toi est le moteur de ton succès, continue de croire en toi-même et en ton travail.",
    "N'oublie pas de prendre du temps pour te ressourcer et prendre soin de toi, cela est essentiel pour ton bien-être.",
    "Ton diplôme de doctorat est à ta portée, continue de travailler avec acharnement pour l'atteindre.",
    "La recherche est un voyage d'exploration et de découverte, continue d'explorer avec passion.",
    "Chaque chapitre que tu écris est une victoire en soi, ne sous-estime pas l'importance de chaque étape.",
    "La créativité et l'innovation sont au cœur de la recherche, et tu es un créateur de connaissances.",
    "Les moments de doute ne font que renforcer ta détermination à réussir, ne les laisse pas te décourager.",
    "Ton travail est une contribution précieuse à la connaissance, ne sous-estime jamais son impact.",
    "Chaque jour apporte de nouvelles opportunités de réussite, saisis-les avec détermination.",
    "Tu as déjà surmonté des obstacles pour en arriver là où tu es, tu es capable de surmonter ceux qui se présentent encore.",
    "La persévérance est la clé pour surmonter les obstacles, continue à avancer avec force et courage.",
    "Lorsque tu te sens dépassé, rappelle-toi pourquoi tu as entrepris cette recherche et la passion qui t'anime.",
    "La science a besoin de chercheurs passionnés comme toi pour avancer et éclairer le monde.",
    "Ton travail de recherche est important, et il laissera une trace durable dans ton domaine.",
    "Les moments de frustration font partie du voyage, mais ils ne doivent pas entamer ta détermination.",
    "Ton enthousiasme pour ta recherche est contagieux, il inspire ceux qui t'entourent.",
    "La patience et la détermination sont les clés pour traverser les moments difficiles.",
    "N'oublie pas que tu es en train de créer de nouvelles connaissances et de repousser les frontières de la compréhension humaine.",
    "Ton travail est précieux, et il mérite d'être célébré à chaque étape.",
    "Chaque petit progrès te rapproche de l'achèvement de ta thèse, continue d'avancer, un pas à la fois.",
    "La confiance en toi est le moteur de ton succès, continue de croire en toi-même et en ton travail.",
    "N'oublie pas de prendre du temps pour te ressourcer et prendre soin de toi, cela est essentiel pour ton bien-être.",
    "Ton diplôme de doctorat est à ta portée, continue de travailler avec acharnement pour l'atteindre.",
    "La recherche est un voyage d'exploration et de découverte, continue d'explorer avec passion.",
    "Chaque chapitre que tu écris est une victoire en soi, ne sous-estime pas l'importance de chaque étape.",
    "La créativité et l'innovation sont au cœur de la recherche, et tu es un créateur de connaissances.",
    "Les moments de doute ne font que renforcer ta détermination à réussir, ne les laisse pas te décourager.",
    "Ton travail est une contribution précieuse à la connaissance, ne sous-estime jamais son impact.",
    "Chaque jour apporte de nouvelles opportunités de réussite, saisis-les avec détermination.",
    "Tu as déjà surmonté des obstacles pour en arriver là où tu es, tu es capable de surmonter ceux qui se présentent encore.",
    "La persévérance est la clé pour surmonter les obstacles, continue à avancer avec force et courage.",
    "Lorsque tu te sens dépassé, rappelle-toi pourquoi tu as entrepris cette recherche et la passion qui t'anime.",
    "La science a besoin de chercheurs passionnés comme toi pour avancer et éclairer le monde.",
    "Ton travail de recherche est important, et il laissera une trace durable dans ton domaine.",
    "Les moments de frustration font partie du voyage, mais ils ne doivent pas entamer ta détermination.",
    "Ton enthousiasme pour ta recherche est contagieux, il inspire ceux qui t'entourent.",
    "La patience et la détermination sont les clés pour traverser les moments difficiles.",
    "N'oublie pas que tu es en train de créer de nouvelles connaissances et de repousser les frontières de la compréhension humaine.",
    "Ton travail est précieux, et il mérite d'être célébré à chaque étape.",
    "Chaque petit progrès te rapproche de l'achèvement de ta thèse, continue d'avancer, un pas à la fois.",
    "La confiance en toi est le moteur de ton succès, continue de croire en toi-même et en ton travail.",
    "N'oublie pas de prendre du temps pour te ressourcer et prendre soin de toi, cela est essentiel pour ton bien-être.",
    "Ton diplôme de doctorat est à ta portée, continue de travailler avec acharnement pour l'atteindre.",
    "La recherche est un voyage d'exploration et de découverte, continue d'explorer avec passion.",
    "Chaque chapitre que tu écris est une victoire en soi, ne sous-estime pas l'importance de chaque étape.",
    "La créativité et l'innovation sont au cœur de la recherche, et tu es un créateur de connaissances.",
    "Les moments de doute ne font que renforcer ta détermination à réussir, ne les laisse pas te décourager.",
    "Ton travail est une contribution précieuse à la connaissance, ne sous-estime jamais son impact.",
    "Chaque jour apporte de nouvelles opportunités de réussite, saisis-les avec détermination.",
    "Tu as déjà surmonté des obstacles pour en arriver là où tu es, tu es capable de surmonter ceux qui se présentent encore.",
    "La persévérance est la clé pour surmonter les obstacles, continue à avancer avec force et courage.",
    "Lorsque tu te sens dépassé, rappelle-toi pourquoi tu as entrepris cette recherche et la passion qui t'anime.",
    "La science a besoin de chercheurs passionnés comme toi pour avancer et éclairer le monde.",
    "Ton travail de recherche est important, et il laissera une trace durable dans ton domaine.",
    "Les moments de frustration font partie du voyage, mais ils ne doivent pas entamer ta détermination.",
    "Ton enthousiasme pour ta recherche est contagieux, il inspire ceux qui t'entourent.",
    "La patience et la détermination sont les clés pour traverser les moments difficiles.",
    "N'oublie pas que tu es en train de créer de nouvelles connaissances et de repousser les frontières de la compréhension humaine.",
    "Ton travail est précieux, et il mérite d'être célébré à chaque étape.",
    "Chaque petit progrès te rapproche de l'achèvement de ta thèse, continue d'avancer, un pas à la fois.",
    "La confiance en toi est le moteur de ton succès, continue de croire en toi-même et en ton travail.",
    "N'oublie pas de prendre du temps pour te ressourcer et prendre soin de toi, cela est essentiel pour ton bien-être.",
    "Ton diplôme de doctorat est à ta portée, continue de travailler avec acharnement pour l'atteindre.",
    "La recherche est un voyage d'exploration et de découverte, continue d'explorer avec passion.",
    "Chaque chapitre que tu écris est une victoire en soi, ne sous-estime pas l'importance de chaque étape.",
    "La créativité et l'innovation sont au cœur de la recherche, et tu es un créateur de connaissances.",
    "Les moments de doute ne font que renforcer ta détermination à réussir, ne les laisse pas te décourager.",
    "Ton travail est une contribution précieuse à la connaissance, ne sous-estime jamais son impact.",
    "Chaque jour apporte de nouvelles opportunités de réussite, saisis-les avec détermination.",
    "Tu as déjà surmonté des obstacles pour en arriver là où tu es, tu es capable de surmonter ceux qui se présentent encore.",
    "La persévérance est la clé pour surmonter les obstacles, continue à avancer avec force et courage."
]

# Convertir les phrases en code Python
code_python = ["f\"{phrase}\"," for phrase in phrases]

# Créer une chaîne unique en joignant toutes les phrases
code_python_str = "\n".join(code_python)

# Afficher le code Python résultant avec les 200 phrases réconfortantes
print(code_python_str)
